# detect if make supports --eval
_EVAL := NO
ifeq ($(_EVAL),YES)
MAKE=$(BACKPORT_DIR)/scripts/make
else
-include .config
endif

export

.PHONY: modules
modules:
	@$(MAKE) -C $(KLIB_BUILD) M=$(BACKPORT_DIR) modules

.PHONY: clean
clean:
	@$(MAKE) -C $(KLIB_BUILD) M=$(BACKPORT_DIR) clean
